on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deployment:
    if: github.event.pull_request.merged == true
    runs-on:
      - self-hosted
    steps:
      - name: Pull repository
        run:
          ssh ${{ secrets.SRUN_SERVER }} "git -C ${{ secrets.DEPLOY_PATH }}/ pull"
      - name: Deploy
        run: |
          ssh ${{ secrets.SRUN_SERVER }} "srun --job-name=deploy_emdb_prep --time=0:30:00 --mem=1g --partition=datamover --chdir=${{ secrets.DEPLOY_PATH }} bash -c 'find . -name \"*.xsd\" -exec cp --parents {} ${{ secrets.FTP_PATH2 }}/ \\;'"
          ssh ${{ secrets.SRUN_SERVER }} "srun --job-name=deploy_emdb_prep --time=0:30:00 --mem=1g --partition=datamover bash -c 'rsync -av ${{ secrets.DEPLOY_PATH }}/emdb_schemas/ ${{ secrets.FTP_PATH }}/'"
      - name: Send e-mail
        run:
          echo "The EMDB schemas repository was pulled and moved to production." | mail -s "[emdb-schema] EMDB schema has updated" pdb_em@ebi.ac.uk
