on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps: 
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@v1.11.1
      with:
        url: 'https://wwwdev.ebi.ac.uk/emdb/jkn/job/emdb_schemas_cd/build?token=emdb_trigger'
        method: 'POST'
        username: ${{ secrets.JENKINS_USERNAME }}
        password: ${{ secrets.JENKINS_API_KEY }}
